/**
 * IVA declaration report DTOs — the support report the org uses to fill (and
 * cross-check) the TRIBU-CR monthly return (formulario D-150, ex D-104).
 *
 * Wire shape is snake_case, mirroring the sales-api DTOs. The full endpoint
 * contract lives in `docs/IVA_TAX_REPORT.md`; this file is the FE half of it.
 *
 * The report is a *reconciliation aid*, never the filing itself: the legal
 * declaration is submitted in TRIBU-CR, which prefills from the documents
 * Hacienda already accepted. `is_final` / `pending_documents` exist so the UI
 * can say out loud when the two sets can still diverge.
 */

import type { IvaDeclarationFormValue } from "@/lib/enums/ivaDeclaration";

// ─── Section I — Ventas (débito fiscal) ───────────────────────────────────

export interface IvaSalesRateRow {
  /** Hacienda `TaxRateCode` (Nota 8.1). */
  rate_code: string;
  /** Percentage the BE resolved for the bucket (13, 4, 2, 1, 0.5, 0). */
  rate_percentage: number;
  /** Base of goods lines (CABYS-classified merchandise). */
  merchandise_base: number;
  /** Base of service lines. */
  service_base: number;
  /** merchandise_base + service_base, after discounts. */
  taxable_base: number;
  /** IVA generated by the bucket. */
  tax_amount: number;
  /** Documents that contributed to the bucket (drill-down affordance). */
  document_count: number;
}

export interface IvaSalesSection {
  rows: IvaSalesRateRow[];
  /** Exempt base (rate code 10) — no debit, no credit right. */
  exempt_base: number;
  /** Non-subject base (rate code 11) — erodes the prorrata numerator. */
  non_taxable_base: number;
  /** Exports (FEE, doc type 09) — 0 % with full credit right. */
  export_base: number;
  taxable_base_total: number;
  /** Débito fiscal del período. */
  tax_debit_total: number;
  /** IVA on sale conditions 10/11 whose payment is deferred up to 90 days. */
  deferred_tax_total: number;
  /** Deferred IVA that became payable this period (REP collected). */
  deferred_tax_collected: number;
  /** Credit notes already netted out of the rows above. */
  credit_note_total: number;
  /** Debit notes already added into the rows above. */
  debit_note_total: number;
}

// ─── Section II — Compras y créditos ──────────────────────────────────────

export interface IvaPurchaseRateRow {
  rate_code: string;
  rate_percentage: number;
  taxable_base: number;
  /** IVA borne on the purchases of the bucket. */
  tax_supported: number;
  /** Portion destined to taxed activity — creditable in full. */
  full_credit_tax: number;
  /** Portion destined to exempt/non-subject activity — not creditable. */
  non_creditable_tax: number;
  /** Mixed-destination portion — subject to the prorrata factor. */
  mixed_tax: number;
  document_count: number;
}

export interface IvaPurchasesSection {
  rows: IvaPurchaseRateRow[];
  taxable_base_total: number;
  tax_supported_total: number;
  full_credit_total: number;
  /** Mixed-use IVA *after* applying the provisional prorrata. */
  mixed_credit_total: number;
  non_creditable_total: number;
  /** Art. 31 RLIVA credit on capital goods amortised over the period. */
  capital_goods_credit: number;
  /** Crédito fiscal del período = full + mixed(prorrated) + capital goods. */
  tax_credit_total: number;
  /**
   * Purchase documents Hacienda has, that the org has NOT accepted yet.
   * Their IVA is not creditable until acceptance — surfaced as a warning.
   */
  unaccepted_document_count: number;
}

// ─── Section III — Proporcionalidad (prorrata) ────────────────────────────

export interface IvaProportionality {
  /** False when the org only performs operations with full credit right. */
  applies: boolean;
  /** Provisional percentage applied during the year (art. 29 RLIVA). */
  provisional_percentage: number;
  /** Definitive percentage — only resolved on the December adjustment. */
  definitive_percentage: number | null;
  /** True when the period is the annual settlement (December). */
  is_annual_adjustment: boolean;
  /** Positive = extra credit recovered; negative = credit to give back. */
  adjustment_amount: number;
  /** Numerator: operations with credit right. */
  credit_bearing_revenue: number;
  /** Denominator: total operations. */
  total_revenue: number;
}

// ─── Section IV — Determinación ───────────────────────────────────────────

export interface IvaDetermination {
  tax_debit: number;
  tax_credit: number;
  /** Section III carry-over into the period result. */
  proportionality_adjustment: number;
  /** Positive when the period settles as tax due. */
  net_tax: number;
  /** Positive when the period settles as a favourable balance. */
  favorable_balance: number;
}

// ─── Section V/VI — Liquidación y resultado ───────────────────────────────

export interface IvaSettlement {
  /** Carried-forward credit from earlier periods. */
  previous_favorable_balance: number;
  /** Up to 6 % retained by card acquirers (art. 15 bis Ley 6826). */
  card_withholdings: number;
  other_withholdings: number;
  advance_payments: number;
  compensations: number;
  interest: number;
  penalties: number;
  /** Final amount to pay in TRIBU-CR. */
  total_payable: number;
  /** Credit that rolls into the next period. */
  carry_forward_balance: number;
  /** ISO date — day 15 of the month following the period. */
  due_date: string;
}

// ─── Warnings ─────────────────────────────────────────────────────────────

/** Machine-readable reasons the report may not match the TRIBU-CR draft. */
export const IVA_WARNING_CODES = [
  "pending_hacienda_validation",
  "rejected_documents",
  "unaccepted_purchases",
  "missing_cabys",
  "manual_orders_excluded",
  "provisional_proportionality",
] as const;
export type IvaWarningCode = (typeof IVA_WARNING_CODES)[number];

export interface IvaReportWarning {
  code: IvaWarningCode;
  /** Documents affected, when the warning is document-scoped. */
  document_count?: number;
  /** Amount at stake, when the warning is money-scoped. */
  amount?: number;
}

// ─── Report root ──────────────────────────────────────────────────────────

export interface IvaReport {
  organization_id: string;
  /** Declared period, `YYYY-MM` (or `YYYY-Qn` for the agro forms). */
  period: string;
  period_start: string;
  period_end: string;
  form_code: IvaDeclarationFormValue;
  /** ISO 4217 — the declaration is always filed in CRC. */
  currency_code: string;
  generated_on: string;
  /** True once every document of the period reached a terminal Hacienda state. */
  is_final: boolean;
  pending_documents: number;
  rejected_documents: number;
  sales: IvaSalesSection;
  purchases: IvaPurchasesSection;
  proportionality: IvaProportionality;
  determination: IvaDetermination;
  settlement: IvaSettlement;
  warnings: IvaReportWarning[];
}

/** `GET /tax-reports/iva/periods` — periods the org has data for. */
export interface IvaReportPeriod {
  period: string;
  form_code: IvaDeclarationFormValue;
  is_final: boolean;
  /** Convenience mirror of `settlement.total_payable` for the picker. */
  total_payable: number;
  due_date: string;
}
